// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ugyfel;
//
//    var tagdij = Tagdij.FromJson(jsonString);

namespace ugyfel
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Tagdij
    {
        [JsonProperty("azon")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Azon { get; set; }

        [JsonProperty("nev")]
        public string Nev { get; set; }

        [JsonProperty("szulev")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Szulev { get; set; }

        [JsonProperty("irszam")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Irszam { get; set; }

        [JsonProperty("orsz")]
        public string Orsz { get; set; }
    }

    public partial class Tagdij
    {
        public static Tagdij[] FromJson(string json) => JsonConvert.DeserializeObject<Tagdij[]>(json, ugyfel.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Tagdij[] self) => JsonConvert.SerializeObject(self, ugyfel.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
